title: Hướng dẫn giải một số bài trên Code Learn
description: Hướng dẫn giải một số bài trên Code Learn
author: "Code Learn Solution"
github: //github.com/vnspoj/code-learn
about: Hướng dẫn giải một số bài trên Code Learn
disqus_shortname: codelearnsolution
# google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/favicon.png
email: tutorialspoj@gmail.com

username: vnspoj
repo: code-learn
org: //github.com/vnspoj

social:
    - icon: fa-stack-overflow
      link: "//stackoverflow.com/users/8828489/huynhsamha"
    - icon: fa-github
      link: "//github.com/vnspoj"
    - icon: fa-twitter
      link: "//twitter.com/huynhsamha"
    - icon: fa-linkedin
      link: "//www.linkedin.com/in/huynhsamha"

share:
  twitter_username: huynhsamha
  # fb_appid: 1749788565247320

urls:
    - text: About Us
      url: /about
    - text: Related Topics
      url: /category
    - text: Contests
      url: /contests
    - text: XML Feed
      url: /feed.xml

collections:
    contests:
      output: true

url: "//vnspoj.github.io"
baseurl: "/code-learn"
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
# mathjax: true
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all

sass:
  style: compressed
